version: '3'

services:

  angular:
    container_name: angulartest
    build: ./AppAngular/app/
    image: angular:v2
    ports:
      - 4200:4200
    expose :
      - 4200
    networks:
      - internalnet 
      
  express:
    container_name: expresstest
    build: ./AppExpress/express-gen-ts/
    image: express:v1
    ports:
      - 3000:3000
    expose :
      - 3000
    networks:
      - internalnet
    #depends_on:
    #  - angular

networks:
  internalnet:
    driver: bridge